server:
  name: netserver_test
  author: airing
  version: 1.0
  port: 8045
  netTimeOutMs: 5000
  capacityPool: 10000
  capacityLimit: 10000
  idleTimeoutMs: 900000

log:
  level: debug
  path: ../log/
  maxSize: 100   #mb
  maxBackups: 20 #file count
  maxAge: 30     #days
  compress: true

etcd:
  addrs: ["127.0.0.1:2380"]